# PLUGINS
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# END PLUGINS

# BINDINGS
# Move between panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
# Copy mode bindings
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
# Tmux prefix
unbind-key C-b
set -g prefix C-f
bind-key C-f send-prefix
# Tmux configuration file reload
unbind r
bind r source-file ~/.tmux.conf; display "Reloaded tmux configuration"
# Tmux copy mode
# unbind-key {
# bind-key { copy-mode
# END BINDINGS

# OPTIONS
# Tmux session numbering
set -g base-index 1
set -g renumber-windows on
# Allow showing images
set -gq allow-passthrough on
# Set the default terminal mode to 256 colors
set-option -sa terminal-overrides ",xterm*:Tc"
# Enable mouse support for scrolling, resizing panes, and selecting windows
set -g mouse on
setw -g mode-keys vi
# Move statusbar
# set-option -g status-position bottom
# set -g focus-events on
# set -g status-style bg=default
# set -g status-justify right
# Remove statusbar
set-option -g status off
bind-key S set -g status
# Set the default terminal to support 256 colors and enable cursor shape changes
set -g default-terminal "tmux-256color"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
# END OPTIONS

source-file "~/.config/tmux/themes/showdir.conf"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
run-shell ~/clone/path/yank.tmux
