cursor_blink_interval 0.5
cursor_shape block
cursor_trail 10
cursor_trail_decay 0.02 0.1
cursor_trail_start_threshold 0



font_size 14
# BEGIN_KITTY_THEME
# Vague
include current-theme.conf
# END_KITTY_THEME
